name: Deploy via SCP

on:
  push:
    branches:
      - main  # deploy only when pushing to main branch
  workflow_dispatch:    # allow manual runs from the GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy files via SFTP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "./*"
          target: /home/dh_ci77k2/niclacombe.ca/test/