name: Deploy to FTP

on:
  push:
    branches:
      - main  # or any branch you want to watch for deploys

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to FTP
        uses: appleboy/scp-action
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /home/dh_ci77k2/niclacombe.ca/test/
