name: 🚀 Deploy via FTPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Upload files via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}            # same secret for hostname
          username: ${{ secrets.FTP_USERNAME }}        # same secret for username
          password: ${{ secrets.FTP_PASSWORD }}        # same secret for password
          protocol: ftp                                # 🔥 switch from sftp to ftps
          port: 21                                     # standard explicit FTPS port
          server-dir: /niclacombe.ca/test/             # remote folder (adjust if needed)
          local-dir: ./                                # folder to upload (adjust if you want ./build or another folder)
