name: Deploy to SFTP

on: [push]
  push:
    branches:
      - main  # or any branch you want to watch for deploys
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "./build/*"
          target: /home/dh_ci77k2/niclacombe.ca/test/
