name: Deploy via SFTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload files via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP.USERNAME }}      # same secret for hostname
          username: ${{ secrets.FTP_USERNAME }} # same secret for username
          password: ${{ secrets.FTP_PASSWORD }} # same secret for password (or use 'key' for SSH key)
          port: 22                              # standard SFTP port
          source: "./*"                   # adjust this if needed
          target: "/niclacombe.ca/test/"    # adjust remote path accordingly

