name: Deploy to SFTP

on:
  push:
    branches:
      - main  # or any branch you want to watch for deploys
  workflow_dispatch:

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload via SFTP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "./build/*"
          target: /home/dh_ci77k2/niclacombe.ca/test/
