name: 🚀 Deploy via SFTP CLI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Upload files via sftp
        env:
          SFTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          sshpass -p "$SFTP_PASSWORD" sftp \
            -oBatchMode=no \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            -b - ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} <<EOF
          mkdir -p /home/dh_ci77k2/niclacombe.ca/test/
          put -r ./* niclacombe.ca/test/
          bye
          EOF