name: Deploy via SFTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload via sftp CLI
        env:
          SFTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          sshpass -p "$SFTP_PASSWORD" sftp -oBatchMode=no -b - ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} <<EOF
          put -r ./build/* /niclacombe.ca/test/
          bye
          EOF

